# Generated by Django 4.2.2 on 2023-06-21 17:59

import CarCollection_remake_exam.my_web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sports Car', '1-Sports Car'), ('Pickup', '2-Pickup'), ('Crossover', '3-Crossover'), ('Minibus', '4-Minibus'), ('Other', '5-Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, message='It should consist of a minimum of 2 characters!')])),
                ('year', models.PositiveIntegerField(validators=[CarCollection_remake_exam.my_web.models.validate_car_year])),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Price cannot be below 1!')])),
            ],
        ),
    ]
